lib/registry.ts
package.json
test/registry-test.ts

Using `optionalDependencies` to workaround platform issues means that the problem is just deferred to when you try and import code.
As there's not a good story about being able to conditionally import code based on your platform, let's just let people install the type declarations.

other platforms are a thing

---

src/main.cc

Fixes #17 
I'd incorrectly put `#define UNICODE` _before_ the includes, which meant I was using the ANSI versions of the registry APIs.

force usage of Unicode registry APIs

---

test/registry-test.ts

See discussion about trusting the arguments passed to `ReadValues` from JS: https://github.com/desktop/registry-js/pull/22#issuecomment-349178554

testing we can read values from HKEY_CURRENT_USER

---

src/main.cc

`std::unique_ptr` was passed a `BYTE[]` array but declared as `std::unique_ptr<BYTE>`, which will result in it using the wrong deleter.
Changed to use `std::make_unique` which is a bit simpler.

Correct the use of unique_ptr with array

---

README.md
docs/index.md

The README now calls out straight to the Setup guide, which makes it more clear what you need to build the source correctly...

refine setup instructions

---

src/main.cc

Fixes: #26, also returns once we hit an error in the loop instead of continuing.
(Mostly) stylistic changes:
- Remove a few unneeded buffers and variables
- `sprintf` → `sprintf_s`
- Simplify `DWORD` extraction code (this needs review – is it possible to store non-DWORD data in DWORD entries like you can shove anything into REG_SZ?)
- Use `nullptr`
- Junk `TCHAR` and its ilk
Needed:
- Need to add a test for dodgy non-null-terminated data, but I'm not sure the best way to actually get this _into_ the registry in the first place, since REG.EXE is going to do it correctly. Can we add adjunct C++ programs to the test code somehow?

Æsthetic improvements and two fixes

---

src/main.cc

Found this when running the tests up on Windows 7 - all the tests that expect data fail.
```
$ mocha dist/test/**/*.js
enumerateValue
1) can read strings from the registry
2) can read numbers from the registry
3) can read values from HKCU
√ returns empty array when key is missing
1 passing (0ms)
3 failing
1) enumerateValue
can read strings from the registry:
TypeError: Cannot read property 'type' of undefined
at Context.it (dist\test\registry-test.js:10:43)
2) enumerateValue
can read numbers from the registry:
TypeError: Cannot read property 'type' of undefined
at Context.it (dist\test\registry-test.js:19:42)
3) enumerateValue
can read values from HKCU:
TypeError: Cannot read property 'type' of undefined
at Context.it (dist\test\registry-test.js:25:39)
```
I traced this to `RegOpenKeyEx` …

RegOpenKeyEx needs a proper LPWSTR

---

appveyor.yml

This adds support for testing these versions:
- Node 10.2.1 (basically Electron 3.x) - (10.2.0 has broken headers https://github.com/nodejs/node/issues/20921)
- Node 10.11.0 (the basis for Electron 4.x)
- Node 11.x (latest version)

add additional node versions to test matrix

---

package.json
yarn.lock

`chai` and `mocha` were removed in #59

no need for these @types packages any more

---

src/main.cc

Changed V8::Handle to v8::Local for Node 12.
Ref: http://electronjs.org/blog/nodejs-native-addons-and-electron-5

fix: v8::Handle -> v8::Local for Node 12 compact

---

.gitignore
appveyor.yml
package.json
script/upload.js
yarn.lock

Fixes #34, based heavily on my experiences with `keytar`.

enable prebuild outputs 

---

appveyor.yml

#71 initially failed because `yarn install --force` did not rebuild any native node modules:
```
yarn install --force
yarn install v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
yarn check-prettier
```
Which meant the test failed because it couldn't find the native node module we need:
```
$ jest -c jest.json
FAIL dist/test/registry-test.js
● Test suite failed to run
Cannot find module '../../build/Release/registry.node' from 'registry.js'
However, Jest was able to find:
'./registry.d.ts'
'./registry.js'
'./registry.js.map'
You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].
See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string
However, Jest …
```

disable caching node_modules for the moment

---

package.json

Node 10 is the current LTS, Node 12 is the latest, and Electron 3, 4 and 5 are the current set of maintained versions by the team.

only prebuild the versions currently supported by Node and Electron

---

src/main.cc

This PR fixes v8 deprecations warnings and makes this module context aware. ~~This use `isolate->GetCurrentContext();` instead of `Nan::GetCurrentContext()` if needed I'm can change to second implementation.~~
Fixes #143

fix: v8 deprecations warnings and make module context aware

---

package.json
yarn.lock

This PR adds prebuild targets for Electron 7 and updates the node-abi dependency to latest version.
Refers to #170

add prebuild targets for Electron 7

---

package.json
yarn.lock

We're having some issues in Desktop with node-gyp 3.x so we'd like to get onto node-gyp 6.x. Bumping prebuild will do just that and not a whole lot more (see https://github.com/prebuild/prebuild/compare/v9.0.1...v10.0.0).

Bump prebuild to v10

---

package.json

These are very old versions of node and electron, no point in us prebuilding for every version there is.

Drop old versions of node and electron

---

.prettierrc.yml
lib/registry.ts
package.json
yarn.lock

Adds a prettierrc which mirrors current settings as closely as possible. Just the trailing commas are new

Add prettier config file

---

package.json

Preparing to release registry-js 1.10.0.
See diff: https://github.com/desktop/registry-js/compare/v1.9.0...3ed2fde62c2fc98d40d7b3c3fdd7c2bb200573a3
Included PRs:
- #175, #179 automated bumps of sub-dependencies
- #180 thanks @ottosson 
- #182 thanks @pimterry
- #184 Stop prebuilding for node 8 and electron 3, 4, 5, and 6.  
- #183, #185, #186 upgrade typescript, prebuild, ts-node, and prettier to latest versions

Release registry-js 1.10.0

---

.npmignore

When publishing #187 I spotted what I thought was an excessive amount of build artifacts for a package leveraging prebuilt.
```
npm notice package: registry-js@1.10.0
npm notice === Tarball Contents ===
npm notice 1.1kB   LICENSE
npm notice 9.0kB   src/main.cc
npm notice 750B    build/Release/registry.exp
npm notice 2.4kB   build/registry.vcxproj.filters
npm notice 548B    binding.gyp
npm notice 2.5MB   build/Release/registry.ilk
npm notice 658B    dist/lib/index.js
npm notice 2.7kB   dist/test/registry-test.js
npm notice 4.4kB   dist/lib/registry.js
npm notice 47B     jest.json
npm notice 1.8kB   package.json
npm notice 217B    build/Release/obj/registry/registry.tlog/registry.lastbuildstate  
npm notice 1.8kB   build/Release/registry.lib
npm notice 128B    dist/lib/index.js.map
npm …
```

Exclude unnecessary build artifacts from npm package

---

package.json
yarn.lock

Getting a few alerts that there's a vulnerability in on of prebuilt-install's dependencies. I have no reason to believe it would affect `registry-js` in any way but bumping these dependencies will let consumers of `registry-js` avoid automated vulnerability alerts.
prebuild-install changes: https://github.com/prebuild/prebuild-install/compare/v5.2.4...v5.3.5
nan changes: https://github.com/nodejs/nan/compare/v2.10.0...v2.14.1

Bump prebuild-install and nan dependencies

---

package.json

Preparing to release registry-js 1.12.0.
See diff: https://github.com/desktop/registry-js/compare/v1.11.0...ed3ede0
This PR bumps dependencies such that consumers of this package can avoid automated vulnerability alerts. There is no difference in functionality between 1.11.0 and this version.
Included PRs:
- #191 Bump handlebars
- #192 Bump prebuild-install and nan dependencies
- #193 Bump jest and ts-node
- #194 Bump kind-of and bl

Release 1.12.0

---

lib/registry.ts
package-lock.json
package.json
src/main.cc
test/registry-test.ts

In order to implement https://github.com/desktop/desktop/pull/18244, support for writing `REG_EXPAND_SZ` values was needed.
After some investigation, it looks like it's just a string value that might contain expandable variables, so I have reused the logic to set `REG_SZ` values.

Add support for REG_EXPAND_SZ type

---

.github/workflows/ci.yml
package-lock.json
package.json
src/main.cc
yarn.lock

With node@22 and MS VisualStudio 2022 BuildTools on Windows 10, the registry-js package was failing to build via node-gyp.
I had to upgrade to at least node-gyp@9 (latest node-gyp@11) for it to recognize VisualStudio 2022, and then there were build errors with main.cc that after some investigation appeared to need stricter declaration/casting.  I've attempted a reasonable fix based on the errors although I'm not a C/C++ expert.  This now npm installs, builds, and `npm run test` is successful.
```
$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@11.2.0
gyp info using node@22.14.0 | win32 | x64
gyp info find Python using Python version 3.11.6 found at "C:\Python\Python3\python.exe"
gyp info find VS using VS2022 (17.13.35931.197) found at:
gyp info find VS …
```

Fix for MSVC 2022, node 22, on Windows to use more specific declarations+casts.

---

script/upload.js

Closes #283
For some reason, the lack of `shell: true` made the prebuild script fail to run (not sure why now and not in previous releases though 🤷 )

Add shell option to spawnSync in upload script
