desktop/registry-js

.gitattributes, .gitignore, .vscode/extensions.json, .vscode/settings.json, appveyor.yml, binding.gyp, lib/echo.ts, lib/index.ts, package.json, src/main.cc, test/simple-test.ts, tsconfig.json, yarn.lock
=> scaffold the native module code

.gitignore, .npmignore, .vscode/settings.json, benchmarks/reg.ts, binding.gyp, lib/registry.ts, package.json, src/main.cc, test/registry-test.ts, tsconfig.json
Fixes #10
- ~~[ ] what to name it????~~
=> first pass at packaging

README.md, docs/enumerate-values.md, docs/index.md, package.json
=> renaming things

src/main.cc
Trying to make this all a bit more readable. Also, I should avoid doing JS-style braces in C++.
=> correct control flow

src/main.cc, test/registry-test.ts
fixes #19
Also, it looks like `ReadValues` function is wrong (double is casted to `ulong` there and then to `HKEY`).
=> Some fixes

src/main.cc
=> avoid the implicit double cast

src/main.cc
=> update deprecated v8 APIs

appveyor.yml, package.json
=> test on Node 12

README.md, package.json
=> add Node 8 to prebuild matrix

package.json, yarn.lock
=> add prebuild targets for Electron 6

package.json, yarn.lock
Version bump to be able to build for Electron 8 and 9
=> Add prebuild targets for Electron 8 and 9

package.json, yarn.lock
Might as well bump these while we're in here prepping for a release
=> Bump typescript and ts-node

package.json, yarn.lock
Trying to close a few more dependabot alerts. None of these upgrades should affect the behavior of the package for consumers.
=> Even more upgrades

yarn.lock
Seems I messed up at the last second in #193 and missed `bl` and `kind-of`.
=> Last attempt at upgrading dependencies

.npmignore
=> Add src directory to npm package

package.json
#211 Added CreateKey and SetValue functions
#207 Add src directory back to the npm package, so the dependency can be built in those environments where a prebuilt package is not available
=> Release 1.14.0

.github/workflows/ci.yml, binding.gyp, package.json, script/download-node-lib-win-arm64.ps1
Tested this with a pre-release build v0.15.0-rc1 and worked like a charm 😄
=> Enable N-API-based prebuilds

package.json
- #217 and #217 Added N-API support
=> Release v1.15.0

package-lock.json, package.json
- Make sure `createKey` and `setValue` don't return a `number` where they should return a `boolean` (37554b7ed95a1d6c59f94c73704afdf01dac24f4)
- #219 Bump `lodash` from 4.17.19 to 4.17.21
- #220 Bump `hosted-git-info` from 2.7.1 to 2.8.9
=> Release v1.15.1

README.md
Was pointing to the wrong package
=> doc: update reference to node-winreg

package-lock.json, package.json
- Fix for MSVC 2022, node 22, on Windows to use more specific declarations+casts #280 - Thank you, @kmashint!
=> Release v1.16.1
